services:
  - type: web
    name: hair-salon-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hair-salon-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        value: smtp.yandex.ru
      - key: MAIL_PORT
        value: 465
      - key: MAIL_USERNAME
        value: dovar.m@yandex.ru
      - key: MAIL_PASSWORD
        value: hewnpqcyawexnqvy
      - key: MAIL_USE_TLS
        value: True
      - key: MAIL_USE_SSL
        value: False

databases:
  - name: hair-salon-db
    databaseName: hair_salon
    plan: free